export const _COMMANDS = {
	FIND_NODE_MODULES: "001",
	PROGRESS_NODE_MODULES: "002",
	DONE_FIND_NODE_MODULES: "003",
	OPEN_IN_EXPLORER: "004",
	OPEN_WITH_VS_CODE: "005",
	EACH_DIR: '006',
	DELETE_NODE_MODULES: '007',
	CANCELLED_SEARCHING_NODE_MODULES: '008',
	PROGRESS_DELETE_NODE_MODULES: '009',
	TEST: 'TEST',
	GET_SUB_DIRS: 'GET_SUB_DIRS'
}